"""
Human-readable project export — written by the "Create Project & Save" action,
after the human confirms extracted song info and before any LLM interpretation
runs.

This is additive/parallel to the internal UUID-keyed storage tree, never a
replacement for it: the rest of the pipeline keeps reading/writing assets by
project ID exactly as before. This folder exists purely so the artist can find
their project by name in a normal file browser.
"""
import logging
import re
import shutil
from pathlib import Path

from config import settings

logger = logging.getLogger(__name__)


def _sanitize(name: str) -> str:
    name = (name or "").strip()
    name = re.sub(r'[<>:"/\\|?*]', "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


def _unique_folder(root: Path, base_name: str) -> Path:
    """Disambiguate Artist - Title collisions with a numeric suffix rather than
    silently overwriting a previously saved project of the same name."""
    candidate = root / base_name
    if not candidate.exists():
        return candidate
    n = 2
    while (root / f"{base_name} ({n})").exists():
        n += 1
    return root / f"{base_name} ({n})"


def _write_tags(mp3_path: Path, title: str, artist: str, metadata: dict) -> None:
    from mutagen.easyid3 import EasyID3
    from mutagen.id3 import ID3NoHeaderError
    from mutagen.mp3 import MP3

    try:
        tags = EasyID3(str(mp3_path))
    except ID3NoHeaderError:
        # ffmpeg-produced mp3s often have no ID3 header at all yet.
        audio = MP3(str(mp3_path))
        audio.add_tags()
        audio.save()
        tags = EasyID3(str(mp3_path))

    if title:
        tags["title"] = title
    if artist:
        tags["artist"] = artist
    if metadata.get("album"):
        tags["album"] = metadata["album"]
    if metadata.get("composer"):
        tags["composer"] = metadata["composer"]
    tags.save()


def _write_lyrics_md(path: Path, title: str, artist: str, transcript: dict) -> None:
    lines = [f"# {title or 'Untitled'} — {artist or 'Unknown Artist'}", "", "## Lyrics (timestamped)", ""]
    segments = (transcript or {}).get("segments") or []
    if not segments:
        lines.append("_No transcript available._")
    for seg in segments:
        lines.append(f"[{seg.get('start', 0):.1f}s] {seg.get('text', '')}")
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_readme_md(path: Path, title: str, artist: str, metadata: dict) -> None:
    lines = [
        f"# {title or 'Untitled'}",
        f"Artist: {artist or 'Unknown Artist'}",
    ]
    if metadata.get("composer"):
        lines.append(f"Composer: {metadata['composer']}")
    if metadata.get("album"):
        lines.append(f"Album: {metadata['album']}")
    if metadata.get("song_length"):
        lines.append(f"Length: {metadata['song_length']}s")
    if metadata.get("bpm"):
        lines.append(f"BPM: {metadata['bpm']}")
    if metadata.get("musical_key"):
        lines.append(f"Key: {metadata['musical_key']}")
    lines.append("")
    lines.append("Generated by HTXpunk Productions Music Video Generator.")
    path.write_text("\n".join(lines), encoding="utf-8")


def create_human_readable_folder(
    project_id: str,
    title: str,
    artist: str,
    original_audio_path: str,
    converted_audio_path: str,
    transcript: dict,
    metadata: dict,
) -> str:
    """Write the human-readable project export and return its absolute path.

    original_audio_path is copied byte-for-byte (never re-encoded); the
    converted canonical mp3 is copied and re-tagged with the confirmed
    title/artist/album/composer. Either path may be missing (e.g. a remote
    audio URL that failed to resolve locally) — that piece is skipped rather
    than raising, since a partial export is still useful.
    """
    root = Path(settings.local_storage_path) / "HTXpunk Projects"
    root.mkdir(parents=True, exist_ok=True)

    artist_name = _sanitize(artist) or "Unknown Artist"
    title_name = _sanitize(title) or "Untitled"
    folder = _unique_folder(root, f"{artist_name} - {title_name}")
    folder.mkdir(parents=True)
    (folder / "assets").mkdir()

    if original_audio_path and Path(original_audio_path).exists():
        try:
            shutil.copy2(original_audio_path, folder / Path(original_audio_path).name)
        except OSError as e:
            logger.warning("[project_folder] Could not copy original audio: %s", e)

    if converted_audio_path and Path(converted_audio_path).exists():
        tagged_path = folder / f"{artist_name}_{title_name}_HTXpunkMVG.mp3"
        try:
            shutil.copy2(converted_audio_path, tagged_path)
            _write_tags(tagged_path, title, artist, metadata)
        except OSError as e:
            logger.warning("[project_folder] Could not copy converted audio: %s", e)

    _write_lyrics_md(folder / "lyrics.md", title, artist, transcript)
    _write_readme_md(folder / "readme.md", title, artist, metadata)

    logger.info("[project_folder] Created %s for project %s", folder, project_id[:8])
    return str(folder)
